INSERT INTO `CUSTOMER`(LOGIN_ID,CUST_PWD,CUST_NM) VALUES('test1','1234','테스터1');
INSERT INTO `CUSTOMER`(LOGIN_ID,CUST_PWD,CUST_NM) VALUES('test2','1234','테스터2');
INSERT INTO `CUSTOMER`(LOGIN_ID,CUST_PWD,CUST_NM) VALUES('test3','1234','테스터3');
INSERT INTO `CUSTOMER`(LOGIN_ID,CUST_PWD,CUST_NM) VALUES('test4','1234','테스터4');
INSERT INTO `CUSTOMER`(LOGIN_ID,CUST_PWD,CUST_NM) VALUES('test5','1234','테스터5');
INSERT INTO `CUSTOMER`(LOGIN_ID,CUST_PWD,CUST_NM) VALUES('test6','1234','테스터6');
INSERT INTO `CUSTOMER`(LOGIN_ID,CUST_PWD,CUST_NM) VALUES('test7','1234','테스터7');


INSERT INTO CHAT_INFO(ADMIN_IDX,CHAT_TITLE) VALUES (1,'1번 채팅방입니다~');
INSERT INTO CHAT_INFO(ADMIN_IDX,CHAT_TITLE) VALUES (2,'2번 채팅방입니다~');
INSERT INTO CHAT_INFO(ADMIN_IDX,CHAT_TITLE) VALUES (3,'3번 채팅방입니다~');
INSERT INTO CHAT_INFO(ADMIN_IDX,CHAT_TITLE) VALUES (4,'4번 채팅방입니다~');
INSERT INTO CHAT_INFO(ADMIN_IDX,CHAT_TITLE) VALUES (5,'5번 채팅방입니다~');


INSERT INTO CHAT_USER_LIST(CHAT_NO,CUST_IDX) VALUES (1,1);
INSERT INTO CHAT_USER_LIST(CHAT_NO,CUST_IDX) VALUES (2,2);
INSERT INTO CHAT_USER_LIST(CHAT_NO,CUST_IDX) VALUES (3,3);
INSERT INTO CHAT_USER_LIST(CHAT_NO,CUST_IDX) VALUES (4,4);
INSERT INTO CHAT_USER_LIST(CHAT_NO,CUST_IDX) VALUES (5,5);

