-- 1.회원 정보 관련

-- 테이블 생성 SQL - USER
CREATE TABLE USER_INFO
(
    `USER_SEQ`   INT             NOT NULL    AUTO_INCREMENT COMMENT '사용자 INDEX. 사용자 INDEX',
    `LOGIN_ID`   VARCHAR(50)     NOT NULL    COMMENT '로그인 아이디. 로그인 아이디',
    `PASSWORD`   VARCHAR(200)    NOT NULL    COMMENT '비밀번호. 비밀번호',
    `USER_NAME`  VARCHAR(50)     NOT NULL    COMMENT '사용자 이름. 사용자 이름',
    PRIMARY KEY (USER_SEQ)
);

-- Index 설정 SQL - USER(LOGIN_ID)
CREATE INDEX IX_USER_1 ON USER_INFO(LOGIN_ID);

-- 테이블 생성 SQL - LOGIN_HISTORY
CREATE TABLE LOGIN_HISTORY
(
    `LOGIN_HISTORY_SEQ`  INT          NOT NULL    AUTO_INCREMENT COMMENT '로그인 이력 INDEX',
    `USER_SEQ`           INT          NOT NULL    COMMENT '사용자 INDEX',
    `LOGIN_AT`           TIMESTAMP    NOT NULL    COMMENT '로그인 시간',
    PRIMARY KEY (LOGIN_HISTORY_SEQ)
);
-- Index 설정 SQL - LOGIN_HISTORY(LOGIN_AT)
CREATE INDEX IX_LOGIN_HISTORY_1 ON LOGIN_HISTORY(LOGIN_HISTORY_SEQ DESC);
CREATE INDEX IX_LOGIN_HISTORY_2 ON LOGIN_HISTORY(LOGIN_AT DESC);

-- 외래키 설정 SQL - LOGIN_HISTORY(USER_SEQ)
ALTER TABLE `LOGIN_HISTORY`
    ADD CONSTRAINT FK_LOGIN_HISTORY_USER FOREIGN KEY (USER_SEQ) REFERENCES USER_INFO(USER_SEQ)
        ON DELETE CASCADE; -- 사용자 삭제 시 로그인 기록도 삭제

-- 2. 채팅 관련
-- 테이블 생성 SQL - ROOM_INFO
CREATE TABLE ROOM_INFO
(
    `ROOM_SEQ`      INT            NOT NULL    AUTO_INCREMENT COMMENT ' 채팅방 번호',
    `USER_SEQ`    VARCHAR(50)    NOT NULL    COMMENT ' 채팅 생성한 사용자 INDEX',
    `ROOM_TITLE`   VARCHAR(50)    NOT NULL    COMMENT ' 채팅방 제목',
    `ROOM_ENABLE`  CHAR(1)        NOT NULL    DEFAULT 'Y' COMMENT ' 채팅방 활성 여부',
    PRIMARY KEY (ROOM_SEQ)
);
CREATE INDEX IX_ROOM_INFO_1 ON ROOM_INFO(USER_SEQ);

ALTER TABLE `ROOM_INFO`
    ADD CONSTRAINT FK_ROOM_INFO_USER_INFO FOREIGN KEY (USER_SEQ) REFERENCES USER_INFO(USER_SEQ)
        ON DELETE CASCADE; --

-- 테이블 Comment 설정 SQL - CHAT_INFO
-- ALTER TABLE CHAT_INFO COMMENT '채팅방 정보. 채팅방 정보';

-- 테이블 생성 SQL - CHAT_USER_LIST
CREATE TABLE ROOM_USER_LIST
(
    `ROOM_USER_LIST_SEQ`      INT            NOT NULL    AUTO_INCREMENT COMMENT '인덱스',
    `ROOM_SEQ`        INT              NOT NULL    COMMENT '채팅방 번호',
    `USER_SEQ`      INT    NOT NULL    COMMENT '채팅 참여자',
    `JOIN_AT` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '채팅 참여 시간',
    PRIMARY KEY (ROOM_USER_LIST_SEQ)
);
CREATE INDEX IX_ROOM_USER_LIST_1 ON ROOM_USER_LIST(ROOM_USER_LIST_SEQ DESC);
CREATE INDEX IX_ROOM_USER_LIST_2 ON ROOM_USER_LIST(JOIN_AT DESC);

-- 테이블 생성 SQL - CHAT_INFO
CREATE TABLE CHAT_INFO
(
    `CHAT_INFO_SEQ`  INT     NOT NULL    AUTO_INCREMENT COMMENT '채팅 테이블 시퀀스',
    `USER_SEQ`     INT     NULL        COMMENT '채팅 보낸 사용자',
    `ROOM_SEQ`      INT     NULL        COMMENT '채팅방 번호',
    `MSG`          LONGTEXT    NULL        COMMENT '채팅 내용',
    `SEND_AT`      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP        COMMENT '채팅 보낸 시간',
    PRIMARY KEY (CHAT_INFO_SEQ)
);
CREATE INDEX IX_CHAT_INFO_1 ON CHAT_INFO(CHAT_INFO_SEQ DESC);
CREATE INDEX IX_CHAT_INFO_2 ON CHAT_INFO(SEND_AT DESC);

